spring.application.name=demo

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/money-tracking
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Prevent Hibernate from modifying the tables automatically
# spring.jpa.hibernate.ddl-auto=validate

#Flyway properties
spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://localhost:5432/money-tracking
spring.flyway.password= 123456
spring.flyway.user= postgres
spring.flyway.schemas=migrations
spring.flyway.locations=classpath:db/migration
