spring.application.name=demo

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/money-tracking
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Prevent Hibernate from modifying the tables automatically
# spring.jpa.hibernate.ddl-auto=validate

#Flyway properties
spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://localhost:5432/money-tracking
spring.flyway.password= 123456
spring.flyway.user= postgres
spring.flyway.schemas=migrations
spring.flyway.locations=classpath:db/migration

# JWT Configuration
jwt.secret=slfjdtTY6HHHSDGHghgsljgal909000dsajfsldd330dlSecrodd55
# 1 hour in milliseconds:
jwt.expiration=3600000 

# mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_SMTP_USERNAME}
spring.mail.password=${GMAIL_SMTP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Crucial fix for TLS connection failure:
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

